services:
     - type: web
       name: mysite
       env: python
       buildCommand: "./build.sh"
       startCommand: "gunicorn mysite.wsgi:application"
       envVars:
         - key: DEBUG
           value: False
         - key: SECRET_KEY
           generateValue: true
         - key: DJANGO_ALLOWED_HOSTS
           value: .onrender.com