services:
  - type: web
    name: blogging_website-
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn blogging_website-.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: DJANGO_ALLOWED_HOSTS
        value: .onrender.com