# Generated by Django 5.1.1 on 2024-10-11 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_comment_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
