# Generated by Django 5.1.1 on 2024-10-13 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_like_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='bio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
