# Generated by Django 5.1.1 on 2024-10-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_blogpost_slug_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
